name: Transform JSON Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  transform_json:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        pip install beautifulsoup4

    - name: Run JSON to HTML transformation script
      run: |
        python code/render_json_to_html.py ./data/  # Update with your actual script path     

    - name: Commit and push changes to html branch
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout main
        git pull origin main
        git checkout -B html
        git merge --strategy=ours main
        git add ./data/  # Assuming the transformed files are in the `data` folder
        git commit -m "Add transformed HTML files"
        git push origin html --force

    - name: Upload all generated HTML files
      uses: actions/upload-artifact@v4
      with:
        name: rendered-html
        path: '**/data.html'  # Use wildcard to upload all `data.html` files from `data` and subfolders
